/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_image_FTOutline */

#ifndef _Included_generaloss_freetype_image_FTOutline
#define _Included_generaloss_freetype_image_FTOutline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getNContours
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTOutline_getNContours
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    setNContours
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutline_setNContours
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getNPoints
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTOutline_getNPoints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    setNPoints
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutline_setNPoints
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getPoints
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_generaloss_freetype_image_FTOutline_getPoints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    setPoints
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutline_setPoints
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getTags
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_generaloss_freetype_image_FTOutline_getTags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    setTags
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutline_setTags
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getContours
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_generaloss_freetype_image_FTOutline_getContours
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    setContours
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutline_setContours
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTOutline_getFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    setFlags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutline_setFlags
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
