/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_image_FTRasterParams */

#ifndef _Included_generaloss_freetype_image_FTRasterParams
#define _Included_generaloss_freetype_image_FTRasterParams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_image_FTRasterParams_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTRasterParams_freePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    getTarget
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_image_FTRasterParams_getTarget
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    setTarget
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTRasterParams_setTarget
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    getSource
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_image_FTRasterParams_getSource
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    setSource
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTRasterParams_setSource
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    getFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTRasterParams_getFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    setFlags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTRasterParams_setFlags
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    setGraySpans
 * Signature: (JLgeneraloss/freetype/image/FTSpanFunc;)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTRasterParams_setGraySpans
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    setBlackSpans
 * Signature: (JLgeneraloss/freetype/image/FTSpanFunc;)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTRasterParams_setBlackSpans
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    setBitTest
 * Signature: (JLgeneraloss/freetype/image/FTRasterBitTestFunc;)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTRasterParams_setBitTest
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    setBitSet
 * Signature: (JLgeneraloss/freetype/image/FTRasterBitSetFunc;)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTRasterParams_setBitSet
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     generaloss_freetype_image_FTRasterParams
 * Method:    getClipBox
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_image_FTRasterParams_getClipBox
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
