/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_image_FTSpan */

#ifndef _Included_generaloss_freetype_image_FTSpan
#define _Included_generaloss_freetype_image_FTSpan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_image_FTSpan
 * Method:    getX
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_image_FTSpan_getX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTSpan
 * Method:    setX
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTSpan_setX
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     generaloss_freetype_image_FTSpan
 * Method:    getLen
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTSpan_getLen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTSpan
 * Method:    setLen
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTSpan_setLen
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_image_FTSpan
 * Method:    getCoverage
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_image_FTSpan_getCoverage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTSpan
 * Method:    setCoverage
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTSpan_setCoverage
  (JNIEnv *, jclass, jlong, jshort);

#ifdef __cplusplus
}
#endif
#endif
