/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_types_FTBBox */

#ifndef _Included_generaloss_freetype_types_FTBBox
#define _Included_generaloss_freetype_types_FTBBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTBBox_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTBBox_freePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    getXMin
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTBBox_getXMin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    getYMin
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTBBox_getYMin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    getXMax
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTBBox_getXMax
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    getYMax
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTBBox_getYMax
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
