/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_types_FTF26Dot6 */

#ifndef _Included_generaloss_freetype_types_FTF26Dot6
#define _Included_generaloss_freetype_types_FTF26Dot6
#ifdef __cplusplus
extern "C" {
#endif
#undef generaloss_freetype_types_FTF26Dot6_BITS
#define generaloss_freetype_types_FTF26Dot6_BITS 6L
#undef generaloss_freetype_types_FTF26Dot6_UNIT
#define generaloss_freetype_types_FTF26Dot6_UNIT 64L
#undef generaloss_freetype_types_FTF26Dot6_HALF_UNIT
#define generaloss_freetype_types_FTF26Dot6_HALF_UNIT 32L
#undef generaloss_freetype_types_FTF26Dot6_MASK
#define generaloss_freetype_types_FTF26Dot6_MASK 63L
#undef generaloss_freetype_types_FTF26Dot6_UNIT_FRAC
#define generaloss_freetype_types_FTF26Dot6_UNIT_FRAC 0.015625f
/*
 * Class:     generaloss_freetype_types_FTF26Dot6
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTF26Dot6_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_types_FTF26Dot6
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTF26Dot6_freePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTF26Dot6
 * Method:    getRawValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTF26Dot6_getRawValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTF26Dot6
 * Method:    setRawValue
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTF26Dot6_setRawValue
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
