/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_types_FTFixed */

#ifndef _Included_generaloss_freetype_types_FTFixed
#define _Included_generaloss_freetype_types_FTFixed
#ifdef __cplusplus
extern "C" {
#endif
#undef generaloss_freetype_types_FTFixed_BITS
#define generaloss_freetype_types_FTFixed_BITS 16L
#undef generaloss_freetype_types_FTFixed_UNIT
#define generaloss_freetype_types_FTFixed_UNIT 65536LL
#undef generaloss_freetype_types_FTFixed_HALF_UNIT
#define generaloss_freetype_types_FTFixed_HALF_UNIT 32768LL
#undef generaloss_freetype_types_FTFixed_MASK
#define generaloss_freetype_types_FTFixed_MASK 65535LL
#undef generaloss_freetype_types_FTFixed_UNIT_FRAC
#define generaloss_freetype_types_FTFixed_UNIT_FRAC 1.5258789E-5f
/*
 * Class:     generaloss_freetype_types_FTFixed
 * Method:    getRawValue
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTFixed_getRawValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTFixed
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTFixed_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
