/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_types_FTFixed */

#ifndef _Included_generaloss_freetype_types_FTFixed
#define _Included_generaloss_freetype_types_FTFixed
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_types_FTFixed
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTFixed_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_types_FTFixed
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTFixed_freePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTFixed
 * Method:    getRawValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTFixed_getRawValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTFixed
 * Method:    setRawValue
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTFixed_setRawValue
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
