/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_types_FTMatrix */

#ifndef _Included_generaloss_freetype_types_FTMatrix
#define _Included_generaloss_freetype_types_FTMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_types_FTMatrix
 * Method:    getXX
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTMatrix_getXX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTMatrix
 * Method:    getXY
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTMatrix_getXY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTMatrix
 * Method:    getYX
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTMatrix_getYX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTMatrix
 * Method:    getYY
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTMatrix_getYY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTMatrix
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTMatrix_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
