/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_types_FTPos */

#ifndef _Included_generaloss_freetype_types_FTPos
#define _Included_generaloss_freetype_types_FTPos
#ifdef __cplusplus
extern "C" {
#endif
#undef generaloss_freetype_types_FTPos_BITS
#define generaloss_freetype_types_FTPos_BITS 6L
#undef generaloss_freetype_types_FTPos_UNIT
#define generaloss_freetype_types_FTPos_UNIT 64L
#undef generaloss_freetype_types_FTPos_HALF_UNIT
#define generaloss_freetype_types_FTPos_HALF_UNIT 32L
#undef generaloss_freetype_types_FTPos_MASK
#define generaloss_freetype_types_FTPos_MASK 63L
#undef generaloss_freetype_types_FTPos_UNIT_FRAC
#define generaloss_freetype_types_FTPos_UNIT_FRAC 0.015625f
/*
 * Class:     generaloss_freetype_types_FTPos
 * Method:    getRawValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTPos_getRawValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTPos
 * Method:    setRawValue
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTPos_setRawValue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_types_FTPos
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTPos_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
