/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_types_FTVector */

#ifndef _Included_generaloss_freetype_types_FTVector
#define _Included_generaloss_freetype_types_FTVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_types_FTVector
 * Method:    getX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTVector_getX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTVector
 * Method:    setX
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTVector_setX
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     generaloss_freetype_types_FTVector
 * Method:    getY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTVector_getY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTVector
 * Method:    setY
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTVector_setY
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     generaloss_freetype_types_FTVector
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTVector_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
