/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_types_FTBBox */

#ifndef _Included_generaloss_freetype_types_FTBBox
#define _Included_generaloss_freetype_types_FTBBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTBBox_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTBBox_freePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    getXMinRaw
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTBBox_getXMinRaw
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    getYMinRaw
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTBBox_getYMinRaw
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    getXMaxRaw
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTBBox_getXMaxRaw
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTBBox
 * Method:    getYMaxRaw
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTBBox_getYMaxRaw
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
