/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_types_FTVector */

#ifndef _Included_generaloss_freetype_types_FTVector
#define _Included_generaloss_freetype_types_FTVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_types_FTVector
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_types_FTVector_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_types_FTVector
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTVector_freePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTVector
 * Method:    getRawX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTVector_getRawX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTVector
 * Method:    setRawX
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTVector_setRawX
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_types_FTVector
 * Method:    getRawY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_types_FTVector_getRawY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_types_FTVector
 * Method:    setRawY
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_types_FTVector_setRawY
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
