/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_freetype_FTCharMap */

#ifndef _Included_generaloss_freetype_freetype_FTCharMap
#define _Included_generaloss_freetype_freetype_FTCharMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_freetype_FTCharMap
 * Method:    getFace
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTCharMap_getFace
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTCharMap
 * Method:    getEncoding
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTCharMap_getEncoding
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTCharMap
 * Method:    getPlatformID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTCharMap_getPlatformID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTCharMap
 * Method:    getEncodingID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTCharMap_getEncodingID
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
