/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_freetype_FTStream */

#ifndef _Included_generaloss_freetype_freetype_FTStream
#define _Included_generaloss_freetype_freetype_FTStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_freetype_FTStream
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTStream_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_freetype_FTStream
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_freetype_FTStream_freePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTStream
 * Method:    getSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTStream_getSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTStream
 * Method:    setSize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_freetype_FTStream_setSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTStream
 * Method:    getPos
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTStream_getPos
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTStream
 * Method:    setPos
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_freetype_FTStream_setPos
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTStream
 * Method:    setRead
 * Signature: (JLgeneraloss/freetype/freetype/FTStreamIOFunc;)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_freetype_FTStream_setRead
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     generaloss_freetype_freetype_FTStream
 * Method:    setClose
 * Signature: (JLgeneraloss/freetype/freetype/FTStreamCloseFunc;)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_freetype_FTStream_setClose
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     generaloss_freetype_freetype_FTStream
 * Method:    getMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTStream_getMemory
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
