/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_gload_FTGlyphLoad */

#ifndef _Included_generaloss_freetype_gload_FTGlyphLoad
#define _Included_generaloss_freetype_gload_FTGlyphLoad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_gload_FTGlyphLoad
 * Method:    getOutline
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_gload_FTGlyphLoad_getOutline
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoad
 * Method:    getExtraPoints
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_generaloss_freetype_gload_FTGlyphLoad_getExtraPoints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoad
 * Method:    setExtraPoints
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_gload_FTGlyphLoad_setExtraPoints
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoad
 * Method:    getExtraPoints2
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_generaloss_freetype_gload_FTGlyphLoad_getExtraPoints2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoad
 * Method:    setExtraPoints2
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_gload_FTGlyphLoad_setExtraPoints2
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoad
 * Method:    getNumSubglyphs
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_gload_FTGlyphLoad_getNumSubglyphs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoad
 * Method:    setNumSubglyphs
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_gload_FTGlyphLoad_setNumSubglyphs
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoad
 * Method:    getSubglyphs
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_generaloss_freetype_gload_FTGlyphLoad_getSubglyphs
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
