/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_gload_FTGlyphLoader */

#ifndef _Included_generaloss_freetype_gload_FTGlyphLoader
#define _Included_generaloss_freetype_gload_FTGlyphLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_gload_FTGlyphLoader
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_gload_FTGlyphLoader_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoader
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_gload_FTGlyphLoader_freePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoader
 * Method:    getMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_gload_FTGlyphLoader_getMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoader
 * Method:    getMaxPoints
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_gload_FTGlyphLoader_getMaxPoints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoader
 * Method:    getMaxContours
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_gload_FTGlyphLoader_getMaxContours
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoader
 * Method:    getMaxSubglyphs
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_gload_FTGlyphLoader_getMaxSubglyphs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoader
 * Method:    getUseExtra
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_freetype_gload_FTGlyphLoader_getUseExtra
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoader
 * Method:    getBase
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_gload_FTGlyphLoader_getBase
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTGlyphLoader
 * Method:    getCurrent
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_gload_FTGlyphLoader_getCurrent
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
