/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_gload_FTSubGlyph */

#ifndef _Included_generaloss_freetype_gload_FTSubGlyph
#define _Included_generaloss_freetype_gload_FTSubGlyph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_gload_FTSubGlyph
 * Method:    getIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_gload_FTSubGlyph_getIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTSubGlyph
 * Method:    getFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_gload_FTSubGlyph_getFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTSubGlyph
 * Method:    getArg1
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_gload_FTSubGlyph_getArg1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTSubGlyph
 * Method:    getArg2
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_gload_FTSubGlyph_getArg2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_gload_FTSubGlyph
 * Method:    getTransform
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_gload_FTSubGlyph_getTransform
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
