/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_freetype_FTBitmapSize */

#ifndef _Included_generaloss_freetype_freetype_FTBitmapSize
#define _Included_generaloss_freetype_freetype_FTBitmapSize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_freetype_FTBitmapSize
 * Method:    getHeight
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_freetype_FTBitmapSize_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTBitmapSize
 * Method:    getWidth
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_freetype_FTBitmapSize_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTBitmapSize
 * Method:    getSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTBitmapSize_getSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTBitmapSize
 * Method:    getXPpem
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTBitmapSize_getXPpem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTBitmapSize
 * Method:    getYPpem
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTBitmapSize_getYPpem
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
