/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_freetype_FTFace */

#ifndef _Included_generaloss_freetype_freetype_FTFace
#define _Included_generaloss_freetype_freetype_FTFace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getNumFaces
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTFace_getNumFaces
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getFaceIndex
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTFace_getFaceIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getFaceFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTFace_getFaceFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getStyleFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTFace_getStyleFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getNumGlyphs
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTFace_getNumGlyphs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getFamilyName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_generaloss_freetype_freetype_FTFace_getFamilyName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getStyleName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_generaloss_freetype_freetype_FTFace_getStyleName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getNumFixedSizes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTFace_getNumFixedSizes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getAvailableSizes
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_generaloss_freetype_freetype_FTFace_getAvailableSizes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getNumCharmaps
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTFace_getNumCharmaps
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getCharmaps
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_generaloss_freetype_freetype_FTFace_getCharmaps
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getBBox
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTFace_getBBox
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getUnitsPerEM
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTFace_getUnitsPerEM
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getAscender
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_freetype_FTFace_getAscender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getDescender
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_freetype_FTFace_getDescender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getHeight
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_freetype_FTFace_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getMaxAdvanceWidth
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_freetype_FTFace_getMaxAdvanceWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getMaxAdvanceHeight
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_freetype_FTFace_getMaxAdvanceHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getUnderlinePosition
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_freetype_FTFace_getUnderlinePosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getUnderlineThickness
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_freetype_FTFace_getUnderlineThickness
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getGlyph
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTFace_getGlyph
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTFace_getSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    getCharmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTFace_getCharmap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTFace
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTFace_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
