/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_freetype_FTGlyphSlot */

#ifndef _Included_generaloss_freetype_freetype_FTGlyphSlot
#define _Included_generaloss_freetype_freetype_FTGlyphSlot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getLibrary
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getLibrary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getFace
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getFace
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getNext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getNext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getGlyphIndex
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getGlyphIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getMetrics
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getMetrics
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getLinearHoriAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getLinearHoriAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getLinearVertAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getLinearVertAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getAdvance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getFormat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getFormat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getBitmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getBitmap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getBitmapLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getBitmapLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getBitmapTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getBitmapTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getOutline
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getOutline
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getNumSubglyphs
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getNumSubglyphs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getSubglyphs
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getSubglyphs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getLsbDelta
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getLsbDelta
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    getRsbDelta
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_getRsbDelta
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphSlot
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphSlot_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
