/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_freetype_FTGlyphMetrics */

#ifndef _Included_generaloss_freetype_freetype_FTGlyphMetrics
#define _Included_generaloss_freetype_freetype_FTGlyphMetrics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_freetype_FTGlyphMetrics
 * Method:    getWidth
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphMetrics_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphMetrics
 * Method:    getHeight
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphMetrics_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphMetrics
 * Method:    getHoriBearingX
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphMetrics_getHoriBearingX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphMetrics
 * Method:    getHoriBearingY
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphMetrics_getHoriBearingY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphMetrics
 * Method:    getHoriAdvance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphMetrics_getHoriAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphMetrics
 * Method:    getVertBearingX
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphMetrics_getVertBearingX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphMetrics
 * Method:    getVertBearingY
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphMetrics_getVertBearingY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphMetrics
 * Method:    getVertAdvance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphMetrics_getVertAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTGlyphMetrics
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTGlyphMetrics_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
