/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_freetype_FTLibrary */

#ifndef _Included_generaloss_freetype_freetype_FTLibrary
#define _Included_generaloss_freetype_freetype_FTLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_freetype_FTLibrary
 * Method:    getMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTLibrary_getMemory
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
