/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_freetype_FTOpenArgs */

#ifndef _Included_generaloss_freetype_freetype_FTOpenArgs
#define _Included_generaloss_freetype_freetype_FTOpenArgs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_freetype_FTOpenArgs
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTOpenArgs_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_freetype_FTOpenArgs
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_freetype_FTOpenArgs_freePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTOpenArgs
 * Method:    getFlags
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTOpenArgs_getFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTOpenArgs
 * Method:    getMemoryBase
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_generaloss_freetype_freetype_FTOpenArgs_getMemoryBase
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTOpenArgs
 * Method:    getMemorySize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTOpenArgs_getMemorySize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTOpenArgs
 * Method:    getPathname
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_generaloss_freetype_freetype_FTOpenArgs_getPathname
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTOpenArgs
 * Method:    getNumParams
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTOpenArgs_getNumParams
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTOpenArgs
 * Method:    getParams
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_generaloss_freetype_freetype_FTOpenArgs_getParams
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
