/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_freetype_FTParameter */

#ifndef _Included_generaloss_freetype_freetype_FTParameter
#define _Included_generaloss_freetype_freetype_FTParameter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_freetype_FTParameter
 * Method:    getTag
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTParameter_getTag
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTParameter
 * Method:    setTag
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_freetype_FTParameter_setTag
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTParameter
 * Method:    getData
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_freetype_freetype_FTParameter_getData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTParameter
 * Method:    setData
 * Signature: (JLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_freetype_FTParameter_setData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     generaloss_freetype_freetype_FTParameter
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTParameter_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
