/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_freetype_FTSizeMetrics */

#ifndef _Included_generaloss_freetype_freetype_FTSizeMetrics
#define _Included_generaloss_freetype_freetype_FTSizeMetrics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_freetype_FTSizeMetrics
 * Method:    getXppem
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTSizeMetrics_getXppem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeMetrics
 * Method:    getYppem
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTSizeMetrics_getYppem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeMetrics
 * Method:    getXScale
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTSizeMetrics_getXScale
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeMetrics
 * Method:    getYScale
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTSizeMetrics_getYScale
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeMetrics
 * Method:    getAscender
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTSizeMetrics_getAscender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeMetrics
 * Method:    getDescender
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTSizeMetrics_getDescender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeMetrics
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTSizeMetrics_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeMetrics
 * Method:    getMaxAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTSizeMetrics_getMaxAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeMetrics
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTSizeMetrics_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
