/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_freetype_FTSizeRequest */

#ifndef _Included_generaloss_freetype_freetype_FTSizeRequest
#define _Included_generaloss_freetype_freetype_FTSizeRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_freetype_FTSizeRequest
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTSizeRequest_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_freetype_FTSizeRequest
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_freetype_FTSizeRequest_freePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeRequest
 * Method:    getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_freetype_FTSizeRequest_getType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeRequest
 * Method:    getWidth
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTSizeRequest_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeRequest
 * Method:    getHeight
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTSizeRequest_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeRequest
 * Method:    getHoriResolution
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTSizeRequest_getHoriResolution
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_freetype_FTSizeRequest
 * Method:    getVertResolution
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_freetype_FTSizeRequest_getVertResolution
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
