/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_charmap_FTCharMap */

#ifndef _Included_generaloss_freetype_charmap_FTCharMap
#define _Included_generaloss_freetype_charmap_FTCharMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_charmap_FTCharMap
 * Method:    getEncoding
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_charmap_FTCharMap_getEncoding
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_charmap_FTCharMap
 * Method:    getPlatformID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_charmap_FTCharMap_getPlatformID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_charmap_FTCharMap
 * Method:    getEncodingID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_charmap_FTCharMap_getEncodingID
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
