/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_glyph_FTGlyphMetrics */

#ifndef _Included_generaloss_freetype_glyph_FTGlyphMetrics
#define _Included_generaloss_freetype_glyph_FTGlyphMetrics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_glyph_FTGlyphMetrics
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphMetrics_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphMetrics
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphMetrics_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphMetrics
 * Method:    getHoriBearingX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphMetrics_getHoriBearingX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphMetrics
 * Method:    getHoriBearingY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphMetrics_getHoriBearingY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphMetrics
 * Method:    getHoriAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphMetrics_getHoriAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphMetrics
 * Method:    getVertBearingX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphMetrics_getVertBearingX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphMetrics
 * Method:    getVertBearingY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphMetrics_getVertBearingY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphMetrics
 * Method:    getVertAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphMetrics_getVertAdvance
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
