/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_glyph_FTGlyphSlot */

#ifndef _Included_generaloss_freetype_glyph_FTGlyphSlot
#define _Included_generaloss_freetype_glyph_FTGlyphSlot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_glyph_FTGlyphSlot
 * Method:    getMetrics
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_glyph_FTGlyphSlot_getMetrics
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphSlot
 * Method:    getLinearHoriAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphSlot_getLinearHoriAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphSlot
 * Method:    getLinearVertAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphSlot_getLinearVertAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphSlot
 * Method:    getAdvanceX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphSlot_getAdvanceX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphSlot
 * Method:    getAdvanceY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphSlot_getAdvanceY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphSlot
 * Method:    getFormat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphSlot_getFormat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphSlot
 * Method:    getBitmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_glyph_FTGlyphSlot_getBitmap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphSlot
 * Method:    getBitmapLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphSlot_getBitmapLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphSlot
 * Method:    getBitmapTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyphSlot_getBitmapTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphSlot
 * Method:    renderGlyph
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_freetype_glyph_FTGlyphSlot_renderGlyph
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_glyph_FTGlyphSlot
 * Method:    getGlyph
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_glyph_FTGlyphSlot_getGlyph
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
