/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_face_FTSize */

#ifndef _Included_generaloss_freetype_face_FTSize
#define _Included_generaloss_freetype_face_FTSize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_face_FTSize
 * Method:    getMetrics
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_face_FTSize_getMetrics
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
