/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_stroker_FTStroker */

#ifndef _Included_generaloss_freetype_stroker_FTStroker
#define _Included_generaloss_freetype_stroker_FTStroker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_stroker_FTStroker
 * Method:    set
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_stroker_FTStroker_set
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     generaloss_freetype_stroker_FTStroker
 * Method:    done
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_stroker_FTStroker_done
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
