/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_stroke_FTStroker */

#ifndef _Included_generaloss_freetype_stroke_FTStroker
#define _Included_generaloss_freetype_stroke_FTStroker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_stroke_FTStroker
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_stroke_FTStroker_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
