/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_system_FTMemory */

#ifndef _Included_generaloss_freetype_system_FTMemory
#define _Included_generaloss_freetype_system_FTMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_system_FTMemory
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_system_FTMemory_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_system_FTMemory
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_system_FTMemory_freePointer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
