/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_system_FTMemory */

#ifndef _Included_generaloss_freetype_system_FTMemory
#define _Included_generaloss_freetype_system_FTMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_system_FTMemory
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_system_FTMemory_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
