/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_FreeType */

#ifndef _Included_generaloss_freetype_FreeType
#define _Included_generaloss_freetype_FreeType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Init_FreeType
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Init_1FreeType
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Done_FreeType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Done_1FreeType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_New_Face
 * Signature: (JLjava/lang/String;J[J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1New_1Face
  (JNIEnv *, jclass, jlong, jstring, jlong, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_New_Memory_Face
 * Signature: (JLjava/nio/ByteBuffer;JJ[J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1New_1Memory_1Face
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Open_Face
 * Signature: (JJJ[J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Open_1Face
  (JNIEnv *, jclass, jlong, jlong, jlong, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Attach_File
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Attach_1File
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Attach_Stream
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Attach_1Stream
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Reference_Face
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Reference_1Face
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Done_Face
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Done_1Face
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Select_Size
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Select_1Size
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Request_Size
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Request_1Size
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Set_Char_Size
 * Signature: (JIIJJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Set_1Char_1Size
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Set_Pixel_Sizes
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Set_1Pixel_1Sizes
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Load_Glyph
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Load_1Glyph
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Load_Char
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Load_1Char
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Set_Transform
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Set_1Transform
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_Transform
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1Transform
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Render_Glyph
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Render_1Glyph
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_Kerning
 * Signature: (JJJIJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1Kerning
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_Track_Kerning
 * Signature: (JJIJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1Track_1Kerning
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Select_Charmap
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Select_1Charmap
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Set_Charmap
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Set_1Charmap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_Charmap_Index
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1Charmap_1Index
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_Char_Index
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1Char_1Index
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_First_Char
 * Signature: (J[J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1First_1Char
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_Next_Char
 * Signature: (JJ[J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1Next_1Char
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Face_Properties
 * Signature: (JJ[J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Face_1Properties
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_Name_Index
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1Name_1Index
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_Glyph_Name
 * Signature: (JJLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1Glyph_1Name
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_Postscript_Name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1Postscript_1Name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_SubGlyph_Info
 * Signature: (JJ[I[J[I[IJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1SubGlyph_1Info
  (JNIEnv *, jclass, jlong, jlong, jintArray, jlongArray, jintArray, jintArray, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_FSType_Flags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1FSType_1Flags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Face_GetCharVariantIndex
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1Face_1GetCharVariantIndex
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Face_GetCharVariantIsDefault
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Face_1GetCharVariantIsDefault
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Face_GetVariantSelectors
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1Face_1GetVariantSelectors
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Face_GetVariantsOfChar
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1Face_1GetVariantsOfChar
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Face_GetCharsOfVariant
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1Face_1GetCharsOfVariant
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_MulDiv
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1MulDiv
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_MulFix
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1MulFix
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_DivFix
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1DivFix
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_RoundFix
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1RoundFix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_CeilFix
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1CeilFix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_FloorFix
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FreeType_FT_1FloorFix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Vector_Transform
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Vector_1Transform
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Library_Version
 * Signature: (J[I[I[I)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Library_1Version
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Face_CheckTrueTypePatents
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_freetype_FreeType_FT_1Face_1CheckTrueTypePatents
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Face_SetUnpatentedHinting
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_freetype_FreeType_FT_1Face_1SetUnpatentedHinting
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_GlyphLoader_New
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1GlyphLoader_1New
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_GlyphLoader_CreateExtra
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1GlyphLoader_1CreateExtra
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_GlyphLoader_Done
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1GlyphLoader_1Done
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_GlyphLoader_Reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1GlyphLoader_1Reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_GlyphLoader_Rewind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1GlyphLoader_1Rewind
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_GlyphLoader_CheckPoints
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1GlyphLoader_1CheckPoints
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_GlyphLoader_CheckSubGlyphs
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1GlyphLoader_1CheckSubGlyphs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_GlyphLoader_Prepare
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1GlyphLoader_1Prepare
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_GlyphLoader_Add
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1GlyphLoader_1Add
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_New_Glyph
 * Signature: (JI[J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1New_1Glyph
  (JNIEnv *, jclass, jlong, jint, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Get_Glyph
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Get_1Glyph
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Glyph_Copy
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Glyph_1Copy
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Glyph_Transform
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Glyph_1Transform
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Glyph_Get_CBox
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Glyph_1Get_1CBox
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Glyph_To_Bitmap
 * Signature: (JIJZ[J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Glyph_1To_1Bitmap
  (JNIEnv *, jclass, jlong, jint, jlong, jboolean, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Done_Glyph
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Done_1Glyph
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Matrix_Multiply
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Matrix_1Multiply
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Matrix_Invert
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Matrix_1Invert
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Outline_GetInsideBorder
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Outline_1GetInsideBorder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Outline_GetOutsideBorder
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Outline_1GetOutsideBorder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_New
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1New
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_Set
 * Signature: (JJIIJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1Set
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_Rewind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1Rewind
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_ParseOutline
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1ParseOutline
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_BeginSubPath
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1BeginSubPath
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_EndSubPath
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1EndSubPath
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_LineTo
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1LineTo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_ConicTo
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1ConicTo
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_CubicTo
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1CubicTo
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_GetBorderCounts
 * Signature: (JI[J[J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1GetBorderCounts
  (JNIEnv *, jclass, jlong, jint, jlongArray, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_ExportBorder
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1ExportBorder
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_GetCounts
 * Signature: (J[J[J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1GetCounts
  (JNIEnv *, jclass, jlong, jlongArray, jlongArray);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_Export
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1Export
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Stroker_Done
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FreeType_FT_1Stroker_1Done
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Glyph_Stroke
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Glyph_1Stroke
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     generaloss_freetype_FreeType
 * Method:    FT_Glyph_StrokeBorder
 * Signature: (JJZZ)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FreeType_FT_1Glyph_1StrokeBorder
  (JNIEnv *, jclass, jlong, jlong, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
