/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_face_FTFace */

#ifndef _Included_generaloss_freetype_face_FTFace
#define _Included_generaloss_freetype_face_FTFace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getFaceFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getFaceFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getStyleFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getStyleFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getNumGlyphs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getNumGlyphs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getNumCharmaps
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getNumCharmaps
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getCharmaps
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_generaloss_freetype_face_FTFace_getCharmaps
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getAscender
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getAscender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getDescender
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getDescender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getMaxAdvanceWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getMaxAdvanceWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getMaxAdvanceHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getMaxAdvanceHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getUnderlinePosition
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getUnderlinePosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getUnderlineThickness
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getUnderlineThickness
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getGlyph
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_face_FTFace_getGlyph
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_face_FTFace_getSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    selectCharmap
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_freetype_face_FTFace_selectCharmap
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    selectSize
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_freetype_face_FTFace_selectSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    setCharSize
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_freetype_face_FTFace_setCharSize
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    setPixelSizes
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_freetype_face_FTFace_setPixelSizes
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    loadGlyph
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_freetype_face_FTFace_loadGlyph
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    loadChar
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_freetype_face_FTFace_loadChar
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    hasKerning
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_generaloss_freetype_face_FTFace_hasKerning
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getKerning
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getKerning
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    getCharIndex
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_face_FTFace_getCharIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_face_FTFace
 * Method:    doneFace
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_face_FTFace_doneFace
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
