/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_glyph_FTGlyph */

#ifndef _Included_generaloss_freetype_glyph_FTGlyph
#define _Included_generaloss_freetype_glyph_FTGlyph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_glyph_FTGlyph
 * Method:    strokeBorder
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_glyph_FTGlyph_strokeBorder
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     generaloss_freetype_glyph_FTGlyph
 * Method:    toBitmap
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_glyph_FTGlyph_toBitmap
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_glyph_FTGlyph
 * Method:    done
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_glyph_FTGlyph_done
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
