/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_FTLibrary */

#ifndef _Included_generaloss_freetype_FTLibrary
#define _Included_generaloss_freetype_FTLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_FTLibrary
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FTLibrary_initFreeType
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_FTLibrary
 * Method:    newMemoryFace
 * Signature: (JLjava/nio/ByteBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FTLibrary_newMemoryFace
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     generaloss_freetype_FTLibrary
 * Method:    newStroker
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_FTLibrary_strokerNew
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTLibrary
 * Method:    done
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_FTLibrary_doneFreeType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_FTLibrary
 * Method:    getLastErrorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_FTLibrary_getLastErrorCode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
