/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_image_FTBitmap */

#ifndef _Included_generaloss_freetype_image_FTBitmap
#define _Included_generaloss_freetype_image_FTBitmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_image_FTBitmap
 * Method:    getRows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTBitmap_getRows
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTBitmap
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTBitmap_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTBitmap
 * Method:    getPitch
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTBitmap_getPitch
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTBitmap
 * Method:    getBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_generaloss_freetype_image_FTBitmap_getBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTBitmap
 * Method:    getNumGray
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTBitmap_getNumGray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTBitmap
 * Method:    getPixelMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTBitmap_getPixelMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTBitmap
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_image_FTBitmap_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
