/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_image_FTOutline */

#ifndef _Included_generaloss_freetype_image_FTOutline
#define _Included_generaloss_freetype_image_FTOutline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getNContours
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_image_FTOutline_getNContours
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getNPoints
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_generaloss_freetype_image_FTOutline_getNPoints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getPoints
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_generaloss_freetype_image_FTOutline_getPoints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getTags
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_generaloss_freetype_image_FTOutline_getTags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getContours
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_generaloss_freetype_image_FTOutline_getContours
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutline
 * Method:    getFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTOutline_getFlags
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
