/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_image_FTOutlineFuncs */

#ifndef _Included_generaloss_freetype_image_FTOutlineFuncs
#define _Included_generaloss_freetype_image_FTOutlineFuncs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_image_FTOutlineFuncs
 * Method:    createPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_image_FTOutlineFuncs_createPointer
  (JNIEnv *, jclass);

/*
 * Class:     generaloss_freetype_image_FTOutlineFuncs
 * Method:    freePointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutlineFuncs_freePointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutlineFuncs
 * Method:    setMoveTo
 * Signature: (JLgeneraloss/freetype/image/FTOutlineMoveToFuncNative;)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutlineFuncs_setMoveTo
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     generaloss_freetype_image_FTOutlineFuncs
 * Method:    setLineTo
 * Signature: (JLgeneraloss/freetype/image/FTOutlineLineToFuncNative;)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutlineFuncs_setLineTo
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     generaloss_freetype_image_FTOutlineFuncs
 * Method:    setConicTo
 * Signature: (JLgeneraloss/freetype/image/FTOutlineConicToFuncNative;)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutlineFuncs_setConicTo
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     generaloss_freetype_image_FTOutlineFuncs
 * Method:    setCubicTo
 * Signature: (JLgeneraloss/freetype/image/FTOutlineCubicToFuncNative;)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutlineFuncs_setCubicTo
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     generaloss_freetype_image_FTOutlineFuncs
 * Method:    getShift
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTOutlineFuncs_getShift
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutlineFuncs
 * Method:    setShift
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutlineFuncs_setShift
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     generaloss_freetype_image_FTOutlineFuncs
 * Method:    getDelta
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_image_FTOutlineFuncs_getDelta
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_image_FTOutlineFuncs
 * Method:    setDelta
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_generaloss_freetype_image_FTOutlineFuncs_setDelta
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
