set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR arm64)

set(OSXCROSS_TARGET oa64)
set(CMAKE_C_COMPILER ${OSXCROSS_TARGET}-clang)
set(CMAKE_CXX_COMPILER ${OSXCROSS_TARGET}-clang++)

set(CMAKE_OSX_SYSROOT /usr/osxcross/SDK/MacOSX12.3.sdk)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_OSX_SYSROOT})