/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_glyph_FTGlyph */

#ifndef _Included_generaloss_freetype_glyph_FTGlyph
#define _Included_generaloss_freetype_glyph_FTGlyph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_glyph_FTGlyph
 * Method:    getLibrary
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_glyph_FTGlyph_getLibrary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyph
 * Method:    getFormat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTGlyph_getFormat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTGlyph
 * Method:    getAdvance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_glyph_FTGlyph_getAdvance
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
