/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generaloss_freetype_glyph_FTBitmapGlyph */

#ifndef _Included_generaloss_freetype_glyph_FTBitmapGlyph
#define _Included_generaloss_freetype_glyph_FTBitmapGlyph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     generaloss_freetype_glyph_FTBitmapGlyph
 * Method:    getRoot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_glyph_FTBitmapGlyph_getRoot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTBitmapGlyph
 * Method:    getLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTBitmapGlyph_getLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTBitmapGlyph
 * Method:    getTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_generaloss_freetype_glyph_FTBitmapGlyph_getTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTBitmapGlyph
 * Method:    getBitmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_glyph_FTBitmapGlyph_getBitmap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     generaloss_freetype_glyph_FTBitmapGlyph
 * Method:    newStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_generaloss_freetype_glyph_FTBitmapGlyph_newStruct
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
